.PHONY: help up down build logs api migrate revision test lint format type-check pre-commit-install clean

help: ## Show available commands
	@grep -E '^[a-zA-Z_-]+:.*?## ' $(MAKEFILE_LIST) | awk 'BEGIN{FS=":.*?## "}{printf "  %-22s %s\n", $$1, $$2}'

up: ## Build images and start all services in the background
	docker compose up -d --build

down: ## Stop all services
	docker compose down

build: ## Rebuild the api image without starting
	docker compose build api

logs: ## Tail api logs
	docker compose logs -f api

api: ## Open a bash shell inside the api container
	docker compose exec api bash

migrate: ## Apply Alembic migrations
	docker compose exec api alembic upgrade head

revision: ## Create an autogenerated Alembic revision  (usage: make revision m="add foo")
	docker compose exec api alembic revision --autogenerate -m "$(m)"

test: ## Run pytest inside the api container
	docker compose exec api pytest -v

lint: ## Run ruff
	docker compose exec api ruff check .

format: ## Format with black + ruff --fix
	docker compose exec api bash -c "black . && ruff check --fix ."

type-check: ## Run mypy
	docker compose exec api mypy .

pre-commit-install: ## Install git pre-commit hooks on the host
	pre-commit install

clean: ## Tear down everything including volumes
	docker compose down -v
