"""Phase 2 initial schema.

Six tables + three enum types. Written by hand rather than autogenerated so
the enum types and array column defaults are explicit and reviewable.

Revision ID: 0001_initial
Revises:
Create Date: 2026-05-16

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


INVESTIGATION_STATUS = (
    "CREATED",
    "ENRICHING",
    "CORRELATING",
    "ANALYZING",
    "REVIEW_REQUIRED",
    "COMPLETED",
    "ARCHIVED",
    "FAILED",
)

EVENT_TYPES = (
    "IOC_INGESTED",
    "IOC_EXTRACTED",
    "IOC_ENRICHED",
    "INVESTIGATION_CREATED",
    "INVESTIGATION_UPDATED",
    "INVESTIGATION_STATE_CHANGED",
    "INVESTIGATION_FAILED",
    "EVIDENCE_RECORDED",
    "ENRICHMENT_FAILED",
)

ENTITY_TYPES = (
    "domain",
    "url",
    "ip",
    "email",
    "hash_md5",
    "hash_sha1",
    "hash_sha256",
    "cve",
    "raw_log",
    "json_payload",
)


def upgrade() -> None:
    investigation_status = postgresql.ENUM(
        *INVESTIGATION_STATUS, name="investigation_status_enum"
    )
    event_type = postgresql.ENUM(*EVENT_TYPES, name="event_type_enum")
    entity_type = postgresql.ENUM(*ENTITY_TYPES, name="entity_type_enum")

    bind = op.get_bind()
    investigation_status.create(bind, checkfirst=True)
    event_type.create(bind, checkfirst=True)
    entity_type.create(bind, checkfirst=True)

    op.create_table(
        "investigations",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(*INVESTIGATION_STATUS, name="investigation_status_enum", create_type=False),
            nullable=False,
            server_default="CREATED",
        ),
        sa.Column("severity", sa.String(length=32), nullable=False, server_default="unknown"),
        sa.Column("summary", sa.String(), nullable=True),
        sa.Column("confidence_score", sa.Float(), nullable=False, server_default="0"),
        sa.Column("schema_version", sa.Integer(), nullable=False, server_default="1"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )

    op.create_table(
        "evidence",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column("source", sa.String(length=128), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw_data", postgresql.JSONB(), nullable=False, server_default=sa.text("'{}'::jsonb")),
        sa.Column("normalized_data", postgresql.JSONB(), nullable=False, server_default=sa.text("'{}'::jsonb")),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("provenance", postgresql.JSONB(), nullable=False),
        sa.Column(
            "linked_entities",
            postgresql.ARRAY(postgresql.UUID(as_uuid=True)),
            nullable=False,
            server_default=sa.text("'{}'::uuid[]"),
        ),
        sa.Column("investigation_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )
    op.create_index("ix_evidence_investigation_id", "evidence", ["investigation_id"])
    op.create_index("ix_evidence_source", "evidence", ["source"])
    op.create_index("ix_evidence_type", "evidence", ["type"])
    op.create_index("ix_evidence_confidence", "evidence", ["confidence"])

    op.create_table(
        "investigation_events",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column(
            "investigation_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("investigations.id", ondelete="CASCADE"),
            nullable=True,
        ),
        sa.Column(
            "event_type",
            postgresql.ENUM(*EVENT_TYPES, name="event_type_enum", create_type=False),
            nullable=False,
        ),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source", sa.String(length=128), nullable=False),
        sa.Column("correlation_id", sa.String(length=128), nullable=True),
        sa.Column("actor", sa.String(length=128), nullable=False, server_default="system"),
        sa.Column("target", sa.String(length=512), nullable=True),
        sa.Column(
            "evidence_refs",
            postgresql.ARRAY(postgresql.UUID(as_uuid=True)),
            nullable=False,
            server_default=sa.text("'{}'::uuid[]"),
        ),
        sa.Column("metadata", postgresql.JSONB(), nullable=False, server_default=sa.text("'{}'::jsonb")),
        sa.Column("confidence", sa.Float(), nullable=False, server_default="1.0"),
    )
    op.create_index(
        "ix_investigation_events_inv_ts",
        "investigation_events",
        ["investigation_id", "timestamp"],
    )
    op.create_index("ix_investigation_events_type", "investigation_events", ["event_type"])

    op.create_table(
        "entity_aliases",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column(
            "entity_type",
            postgresql.ENUM(*ENTITY_TYPES, name="entity_type_enum", create_type=False),
            nullable=False,
        ),
        sa.Column("canonical_form", sa.String(length=2048), nullable=False),
        sa.Column("variants", postgresql.JSONB(), nullable=False, server_default=sa.text("'[]'::jsonb")),
        sa.Column("confidence", sa.Float(), nullable=False, server_default="1.0"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.UniqueConstraint("canonical_form", "entity_type", name="uq_entity_aliases_form_type"),
    )

    op.create_table(
        "enrichment_results",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True, nullable=False),
        sa.Column(
            "ioc_evidence_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("evidence.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("request_fingerprint", sa.String(length=128), nullable=False),
        sa.Column("raw_response", postgresql.JSONB(), nullable=False, server_default=sa.text("'{}'::jsonb")),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("error", sa.String(), nullable=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index(
        "ix_enrichment_results_fingerprint", "enrichment_results", ["request_fingerprint"]
    )
    op.create_index("ix_enrichment_results_ioc", "enrichment_results", ["ioc_evidence_id"])

    op.create_table(
        "idempotency_keys",
        sa.Column("key", sa.String(length=256), primary_key=True, nullable=False),
        sa.Column("response", postgresql.JSONB(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )


def downgrade() -> None:
    op.drop_table("idempotency_keys")
    op.drop_index("ix_enrichment_results_ioc", table_name="enrichment_results")
    op.drop_index("ix_enrichment_results_fingerprint", table_name="enrichment_results")
    op.drop_table("enrichment_results")
    op.drop_table("entity_aliases")
    op.drop_index("ix_investigation_events_type", table_name="investigation_events")
    op.drop_index("ix_investigation_events_inv_ts", table_name="investigation_events")
    op.drop_table("investigation_events")
    op.drop_index("ix_evidence_confidence", table_name="evidence")
    op.drop_index("ix_evidence_type", table_name="evidence")
    op.drop_index("ix_evidence_source", table_name="evidence")
    op.drop_index("ix_evidence_investigation_id", table_name="evidence")
    op.drop_table("evidence")
    op.drop_table("investigations")

    bind = op.get_bind()
    postgresql.ENUM(name="entity_type_enum").drop(bind, checkfirst=True)
    postgresql.ENUM(name="event_type_enum").drop(bind, checkfirst=True)
    postgresql.ENUM(name="investigation_status_enum").drop(bind, checkfirst=True)
