"""Canonical event types.

These are the only event_type values that may appear in
``investigation_events``. Adding a new type requires updating the Postgres
enum via Alembic migration.
"""
from __future__ import annotations

from enum import Enum


class EventType(str, Enum):
    IOC_INGESTED = "IOC_INGESTED"
    IOC_EXTRACTED = "IOC_EXTRACTED"
    IOC_ENRICHED = "IOC_ENRICHED"
    INVESTIGATION_CREATED = "INVESTIGATION_CREATED"
    INVESTIGATION_UPDATED = "INVESTIGATION_UPDATED"
    INVESTIGATION_STATE_CHANGED = "INVESTIGATION_STATE_CHANGED"
    INVESTIGATION_FAILED = "INVESTIGATION_FAILED"
    EVIDENCE_RECORDED = "EVIDENCE_RECORDED"
    ENRICHMENT_FAILED = "ENRICHMENT_FAILED"
    # --- Phase 3: graph engine ---------------------------------------
    GRAPH_NODE_CREATED = "GRAPH_NODE_CREATED"
    GRAPH_RELATIONSHIP_CREATED = "GRAPH_RELATIONSHIP_CREATED"
    GRAPH_MUTATION_REJECTED = "GRAPH_MUTATION_REJECTED"
    CORRELATION_COMPLETED = "CORRELATION_COMPLETED"
    INTEGRITY_VIOLATION_DETECTED = "INTEGRITY_VIOLATION_DETECTED"
    # --- Phase 4: AI firewall ----------------------------------------
    PROMPT_RECEIVED = "PROMPT_RECEIVED"
    PROMPT_ANALYZED = "PROMPT_ANALYZED"
    PROMPT_BLOCKED = "PROMPT_BLOCKED"
    PROMPT_SANITIZED = "PROMPT_SANITIZED"
    PROMPT_REQUIRES_REVIEW = "PROMPT_REQUIRES_REVIEW"
    OUTPUT_VALIDATED = "OUTPUT_VALIDATED"
    OUTPUT_BLOCKED = "OUTPUT_BLOCKED"
    FIREWALL_RULE_FIRED = "FIREWALL_RULE_FIRED"
